apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookstack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/akshmohan/bookstack-k8s.git
    targetRevision: HEAD
    path: base
  destination:
    server: https://kubernetes.default.svc
    namespace: bookstack-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true