apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookstack-dev

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - pvc.yaml
  - mariadb-deployment.yaml  # ADD THIS
  - deployment.yaml          # This is Bookstack
  - service.yaml             # Ensure this file contains BOTH services
  - servicemonitor.yaml